services:
    mailpit:
        image: axllent/mailpit
        ports:
            - ${MAILDEV_PORT}:8025

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            PMA_HOST: mariadb
            PMA_ARBITRARY: 1
        links:
            - mariadb
        volumes:
            - ./.docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        ports:
            - ${PMA_PORT}:80
